---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-dotnet-webapp
  namespace: ynorman
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: demo-dotnet-webapp
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    image: gcr.io/ynorman-project/local-builds
    git:
      ref:
        branch: main
      url: https://github.com/yanivno/demo-dotnet-webapp.git