---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-dotnet-webapp
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: demo-dotnet-webapp
spec:
  source:
    image: gcr.io/ynorman-project/local-builds
    git:
      ref:
        branch: main
      url: https://github.com/yanivno/demo-dotnet-webapp.git