---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: demo-dotnet-webapp
  namespace: ynorman
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: demo-dotnet-webapp
spec:
  env:
  - name: RABBITMQ_URL
    value: "my-rabbit:5672"
#  - name: SECRET_VALUE_ENV
#    valueFrom:
#      secretKeyRef:
#        name: schemapass
#        key: password
  params:
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: dotnet
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    image: gcr.io/ynorman-project/local-builds
    git:
      ref:
        branch: main
      url: https://github.com/yanivno/demo-dotnet-webapp.git